AWSTemplateFormatVersion: 2010-09-09

Description: Master CloudFormation Script to Deploy Onica Stack

Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/onica-jameschen/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName:    !Ref AWS::StackName
        VpcCIDR:            10.0.0.0/16
        PublicSubnet1CIDR:  10.0.0.0/24
        PublicSubnet2CIDR:  10.0.1.0/24
        PrivateSubnet1CIDR: 10.0.10.0/24
        PrivateSubnet2CIDR: 10.0.11.0/24

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/onica-jameschen/infrastructure/securitygroups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  EC2WithLoadBalancers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/onica-jameschen/infrastructure/ec2withloadbalancers.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
        PrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
        PublicSubnets: !GetAtt VPC.Outputs.PublicSubnets
        LoadBalancerSecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
        WebServerSecurityGroup: !GetAtt SecurityGroups.Outputs.WebServerSecurityGroup
        InstanceType: t2.micro
        MinSize: 2
        MaxSize: 4
